/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.univalle.guiInterfacesLab2023.view;

import com.univalle.guiInterfacesLab2023.controller.MainViewController;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author juane
 */
public class MainView extends JFrame {
    private final MainViewController mainFrameController;
        
    /**
     * Creates new form myGui
     */
    public MainView() {
        initComponents();
        
        mainFrameController = new MainViewController(this);
        
        mainFrameController.addActionListeners();
        mainFrameController.addItemListeners();
        
        comboSignalA.setSelectedIndex(1);
        comboSignalD.setSelectedIndex(1);
        comboSignalA.setSelectedIndex(0);
        comboSignalD.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionSenal = new javax.swing.ButtonGroup();
        signalPanel = new javax.swing.JPanel();
        comboSignalD = new javax.swing.JComboBox<>();
        comboSignalA = new javax.swing.JComboBox<>();
        sampleRateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        signalD = new javax.swing.JRadioButton();
        signalA = new javax.swing.JRadioButton();
        SelectButton = new javax.swing.JButton();
        DO0 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DO1 = new javax.swing.JToggleButton();
        DO2 = new javax.swing.JToggleButton();
        DO3 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        lineChartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        signalPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comboSignalD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D0", "D1", "D2", "D3" }));

        comboSignalA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7" }));
        comboSignalA.setSelectedItem(comboSignalA);

        sampleRateTextField.setText("100");
        sampleRateTextField.setToolTipText("");

        jLabel3.setText("Tiempo de muestreo");

        seleccionSenal.add(signalD);
        signalD.setText("Señales Digitales");

        seleccionSenal.add(signalA);
        signalA.setText("Señales Analógicas");

        SelectButton.setBackground(new java.awt.Color(204, 255, 204));
        SelectButton.setText("Seleccionar");

        DO0.setText("DO0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Inputs Signals");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Outputs DIgital Signals");

        DO1.setText("DO1");

        DO2.setText("DO2");

        DO3.setText("DO3");

        jLabel4.setText("ms");

        javax.swing.GroupLayout signalPanelLayout = new javax.swing.GroupLayout(signalPanel);
        signalPanel.setLayout(signalPanelLayout);
        signalPanelLayout.setHorizontalGroup(
            signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signalPanelLayout.createSequentialGroup()
                        .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signalD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signalPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(comboSignalA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signalPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(comboSignalD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(signalPanelLayout.createSequentialGroup()
                                        .addComponent(DO2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DO3))
                                    .addGroup(signalPanelLayout.createSequentialGroup()
                                        .addComponent(DO0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DO1)))))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signalPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(sampleRateTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signalPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(SelectButton))
                .addGap(17, 17, 17))
            .addGroup(signalPanelLayout.createSequentialGroup()
                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(signalA))
                    .addGroup(signalPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signalPanelLayout.setVerticalGroup(
            signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signalA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSignalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signalD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboSignalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sampleRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addComponent(SelectButton)
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DO0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DO1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DO2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DO3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lineChartPanelLayout = new javax.swing.GroupLayout(lineChartPanel);
        lineChartPanel.setLayout(lineChartPanelLayout);
        lineChartPanelLayout.setHorizontalGroup(
            lineChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        lineChartPanelLayout.setVerticalGroup(
            lineChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lineChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lineChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton DO0;
    private javax.swing.JToggleButton DO1;
    private javax.swing.JToggleButton DO2;
    private javax.swing.JToggleButton DO3;
    private javax.swing.JButton SelectButton;
    private javax.swing.JComboBox<String> comboSignalA;
    private javax.swing.JComboBox<String> comboSignalD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel lineChartPanel;
    private javax.swing.JTextField sampleRateTextField;
    private javax.swing.ButtonGroup seleccionSenal;
    private javax.swing.JRadioButton signalA;
    private javax.swing.JRadioButton signalD;
    private javax.swing.JPanel signalPanel;
    // End of variables declaration//GEN-END:variables
   
    public JToggleButton getDO0() {
        return DO0;
    }

    public JToggleButton getDO1() {
        return DO1;
    }

    public JToggleButton getDO2() {
        return DO2;
    }

    public JToggleButton getDO3() {
        return DO3;
    }

    public JButton getSelectButton() {
        return SelectButton;
    }

    public JComboBox<String> getComboSignalA() {
        return comboSignalA;
    }

    public JComboBox<String> getComboSignalD() {
        return comboSignalD;
    }

    public JTextField getSampleRateTextField() {
        return sampleRateTextField;
    }

    public ButtonGroup getSeleccionSenal() {
        return seleccionSenal;
    }

    public JRadioButton getSignalA() {
        return signalA;
    }

    public JRadioButton getSignalD() {
        return signalD;
    }
   
    public JPanel getLineChartPanel() {
        return lineChartPanel;
    }

    public void setLineChartPanel(JPanel lineChartPanel) {
        this.lineChartPanel = lineChartPanel;
    }
    
    
}
